config/routes.rb
TrainToSend::Application.routes.draw do

  get 'home/index'

  devise_for :users, controllers: { sessions: "users/sessions" }

  authenticate :user do
    resources :climbs do
      get "delete"

      resources :attempts
    end
    get 'quick_send', to: 'climbs#quick_new', as: 'climbs_quick_send_new'
    post 'quick_send', to: 'climbs#quick_create', as: 'climbs_quick_send_create'
    get 'sync_mountain_project', to: 'climbs#sync_mountain_project', as: 'climbs_sync_mountain_project'

    resources :exercise_metrics do
      get "delete"
    end

    resources :exercises, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
    end

    resources :workouts, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
      get "assign", to: 'workouts#assign_new'
      post "assign", to: 'workouts#assign_create'
    end

    resources :macrocycles, only: [:index, :new, :create, :edit, :update, :destroy], :path => "plans" do
      get "delete"
      get "duplicate"
      get "assign", to: 'macrocycles#assign_new'
      post "assign", to: 'macrocycles#assign_create'
    end

    resources :events do
      get "delete"
      get "complete"
      get "print"
    end
    get 'gym_session', to: 'events#gym_session_new'
    post 'gym_session', to: 'events#gym_session_create'
    get 'self_assessment', to: 'events#self_assessment'
    get 'self_assessment/new', to: 'events#self_assessment_new', as: 'self_assessment_new'

    get 'profile', to: 'profile#show'
    get 'profile/edit', to: 'profile#edit'
    get 'profile/start_mountain_project', to: 'profile#start_mountain_project'
    patch 'profile/connect_mountain_project', to: 'profile#connect_mountain_project'
    get 'profile/disconnect_mountain_project', to: 'profile#disconnect_mountain_project'
    get 'profile/progress', to: 'profile#progress'
    get 'profile/:user_id/progress', to: 'profile#progress', as: 'profile_user_progress'
    get 'profile/:user_id/schedule', to: 'profile#schedule', as: 'profile_user_schedule'
    get 'profile/:user_id/events/new', to: 'events#new', as: 'profile_user_events_new'
    get 'profile/:user_id/events/create', to: 'events#create', as: 'profile_user_events_create'
    patch 'profile', to: 'profile#update'

    resources :user_coaches, :path => "coaches", only: [:new, :create, :destroy] do
      get "delete"
    end
    get "coaches/my_students", to: 'user_coaches#my_students'

    resources :users, only: [:index, :show] do
      get "impersonate"
    end
    get "stop_impersonating", to: 'users#stop_impersonating'

    resources :item_shares, :path => "share" do
      get "accept"
      get "reject"
    end

    get 'community/training', to: 'community#training'
    get 'community/my_users', to: 'community#my_users'
    get 'community/my_followers', to: 'community#my_followers'
    get 'community/users/follow/:user_id', to: 'community#user_follow', as: 'community_user_follow'
    get 'community/users/unfollow/:user_id', to: 'community#user_unfollow', as: 'community_user_unfollow'

    resources :goals do
      get "delete"
    end

    resources :messages, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end
    get 'inbox/unread', to: 'messages#inbox_unread', as: 'messages_inbox_unread'
    get 'inbox', to: 'messages#inbox', as: 'messages_inbox'

    resources :votes, only: [:new]

    resources :articles, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end

    get 'comment', to: 'comments#new'
    post 'comment', to: 'comments#create'

    get 'onboarding', to: 'users#onboarding'
    get 'onboarding_skip', to: 'users#onboarding_skip'

  end

  resources :messages, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :exercises, only: [:show]
  resources :workouts, only: [:show]
  resources :macrocycles, only: [:show], :path => "plans"
  get 'community/users', to: 'community#users'
  get 'community/users/:user_id', to: 'community#user', as: 'community_user'

  get 'privacy_policy', to: 'home#privacy_policy'
  get 'terms_of_service', to: 'home#terms_of_service'

  root to: "home#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent_message, class_name: 'Message', foreign_key: 'parent_message_id'
  has_many :replies, class_name: 'Message', foreign_key: 'parent_message_id', dependent: :destroy
  belongs_to :messageable, polymorphic: true
  has_many :votes, as: :voteable, dependent: :destroy
  after_create :auto_upvote, :transfer_messageable

  def auto_upvote
    Vote.item_auto_upvote(self)
  end

  def transfer_messageable
    if self.parent_message.present? && self.parent_message.messageable.present?
      self.update_attributes({messageable_id: self.parent_message.messageable_id, messageable_type: self.parent_message.messageable_type})
    end
  end

  def replies_ordered
    self.replies.sort_by{|x| [Vote.item_score(x), x.updated_at]}.reverse
  end

  def self.item_messages_ordered(messageable)
    messageable.messages.where(parent_message_id: nil).sort_by{|x| [Vote.item_score(x), x.updated_at]}.reverse
  end

  def smart_title
    if self.title.present?
      self.title
    elsif self.messageable.present?
      case self.messageable_type
      when "User"
        "From #{self.user.smart_name}"
      when "Exercise"
        "Re: Exercise \"#{self.messageable.label}\""
      when "Workout"
        "Re: Workout \"#{self.messageable.label}\""
      when "Macrocycle"
        "Re: Plan \"#{self.messageable.label}\""
      when "Goal"
        "Re: Goal \"#{self.messageable.label}\""
      when "Article"
        "Re: Article \"#{self.messageable.title}\""
      else

      end
    elsif self.parent_message.present?
      "Re: #{self.parent_message.user.smart_name}'s message"
    else
    end
  end

  def smart_creation_title
    if self.title.present?
      self.title
    elsif self.messageable.present?
      case self.messageable_type
      when "User"
        "Message #{self.user.smart_name}"
      when "Exercise"
        "Discuss Exercise \"#{self.messageable.label}\""
      when "Workout"
        "Discuss Workout \"#{self.messageable.label}\""
      when "Macrocycle"
        "Discuss Plan \"#{self.messageable.label}\""
      when "Goal"
        "Discuss Goal \"#{self.messageable.label}\""
      when "Article"
        "Discuss Article \"#{self.messageable.title}\""
      else

      end
    elsif self.parent_message.present?
      "Respond to #{self.parent_message.user.smart_name}'s message"
    else
      "Start Discussion"
    end
  end

  def belongs_to_user(user)
    self.messageable == user || (self.messageable.present? && self.messageable.user == user) || (self.parent_message.present? && self.parent_message.user == user)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  helper_method :page, :per_page

  def index
    require 'will_paginate/array'
    @messages = Message.where(parent_message_id: nil, messageable_id: nil).sort_by{|x| [Vote.item_score(x), x.updated_at]}.reverse
    @messages = @messages.paginate(:page => page, :per_page => per_page)
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @messages, status: :ok, location: @messages }
    end
  end

  def show
    @primary_message = Message.find_by_id(params[:id])
    if @primary_message.belongs_to_user(current_user) && @primary_message.read.blank?
      @primary_message.read = true
      @primary_message.save
    end

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @primary_message, status: :ok, location: @primary_message }
    end
  end

  def new
    @message = Message.new()
    @message.user_id = current_user.id
    @primary_message_id = params[:primary_message_id]
    if params[:parent_message_id].present?
      @message.parent_message_id = params[:parent_message_id]
    end
    if params[:messageable_id].present? && params[:messageable_type].present?
      @message.messageable_id = params[:messageable_id]
      @message.messageable_type = params[:messageable_type]
    end
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @message, status: :created, location: @message }
    end
  end

  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    if params[:primary_message_id].present?
      @primary_message = Message.find_by_id(params[:primary_message_id])
    else
      @primary_message = @message
    end

    respond_to do |format|
      if @message.save
        require 'will_paginate/array'
        @messages = Message.where(parent_message_id: nil, messageable_id: nil).sort_by{|x| [Vote.item_score(x), x.updated_at]}.reverse
        @messages = @messages.paginate(:page => page, :per_page => per_page)
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.js
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @message = current_user.sent_messages.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @message, status: :ok, location: @message }
    end
  end

  def update
    @message = current_user.sent_messages.find_by_id(params[:id])
    if params[:primary_message_id].present?
      @primary_message = Message.find_by_id(params[:primary_message_id])
    else
      @primary_message = @message
    end
    respond_to do |format|
      if @message.update_attributes(message_params)
        require 'will_paginate/array'
        @messages = Message.where(parent_message_id: nil, messageable_id: nil).sort_by{|x| [Vote.item_score(x), x.updated_at]}.reverse
        @messages = @messages.paginate(:page => page, :per_page => per_page)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.js
        format.json { render json: @message, status: :ok, location: @message }
      else
        format.html
        format.js
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @message = current_user.sent_messages.find_by_id(params[:message_id])
    if params[:primary_message_id].present?
      @primary_message = Message.find_by_id(params[:primary_message_id])
    else
      @primary_message = @message
    end
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def destroy
    @message = current_user.sent_messages.find_by_id(params[:id])
    @message.deleted = true
    if params[:primary_message_id].present?
      @primary_message = Message.find_by_id(params[:primary_message_id])
    else
      @primary_message = @message
    end
    respond_to do |format|
      if @message.save
        require 'will_paginate/array'
        @messages = Message.where(parent_message_id: nil, messageable_id: nil).sort_by{|x| [Vote.item_score(x), x.updated_at]}.reverse
        @messages = @messages.paginate(:page => page, :per_page => per_page)
        format.html { redirect_to @message, notice: 'Message was successfully deleted.' }
        format.js
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def inbox_unread
    require 'will_paginate/array'
    @new_messages = current_user.new_messages
    @new_messages = @new_messages.paginate(:page => page, :per_page => per_page)
  end

  def inbox
    require 'will_paginate/array'
    @all_messages = current_user.all_messages
    @all_messages = @all_messages.paginate(:page => page, :per_page => per_page)
  end

  private

  def message_params
    params.require(:message).permit(:title, :body, :parent_message_id, :messageable_id,
                                    :messageable_type, :read, :views, :deleted)
  end

  def page
    (params[:page] || 1).to_i
  end

  def per_page
    (params[:per_page] || 20).to_i
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_delete.html.erb
<% @primary_message_id = defined?(@primary_message) ? @primary_message.id : nil %>
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Message</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete this message?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Message", message_path(@message, primary_message_id: @primary_message_id), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/messages/_edit.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Message</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/messages/_form.html.erb
<%= form_for(@message, remote: true) do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>
    <%= hidden_field_tag "message[parent_message_id]", @message.parent_message_id %>
    <%= hidden_field_tag "primary_message_id", @primary_message_id %>
    <%= hidden_field_tag "message[messageable_id]", @message.messageable_id %>
    <%= hidden_field_tag "message[messageable_type]", @message.messageable_type %>
    <% unless @message.parent_message_id.present? || @message.messageable_id.present? %>
      <div class="row">
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <%= f.label :body %><br>
          <%= f.text_area :body, class: "form-control", size: "60x3" %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <input type="submit" class="btn btn-primary" value="Save">
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="panel panel-default" data-message-id="<%= message.id %>">
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-1">
        <div class="voting_area" data-voteable-item="Message<%= message.id %>">
          <%= render partial: "votes/voting_area", object: message, as: 'voteable', locals: {} %>
        </div>
      </div>
      <div class="col-xs-11">
        <%= link_to message.smart_title, message_path(message), class: "message_title" %>
        <div>
          <% if message.deleted.present? %>
            <em class="text-muted">Deleted by user.</em>
          <% else %>
            <%= simple_format(truncate(message.body, length: 50, separator: ' ')) %>
          <% end %>
        </div>
        <div>
          <%= link_to message.user.smart_name, community_user_path(message.user.id) %>&nbsp;&nbsp;
          <span class="message_score"><%= "#{pluralize(Vote.item_score(message), 'point')}" %></span>&nbsp;&nbsp;
          <span class="time_ago"><%= time_ago_in_words(message.created_at) %> ago</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/_message_body.html.erb
<% if @primary_message.deleted.present? %>
  <em class="text-muted">Deleted by user.</em>
<% else %>
  <%= @primary_message.body %>
<% end %>

app/views/messages/_messaging_area.html.erb
<div class="row">
  <div class="col-xs-9">
    <h3>Comments</h3>
  </div>
  <div class="col-xs-3 text-right">
    <% if user_signed_in? %>
      <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span> Comment"), new_message_path(messageable_id: messageable.id, messageable_type: messageable.class.name), remote: true, class: "btn btn-success margin_top" %>
    <% end %>
  </div>
</div>

<div class="messageable_message_list">
  <%= render partial: "messages/replies", object: messageable, as: 'messageable' %>
</div>

app/views/messages/_new.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel"> <%= @message.smart_creation_title %></h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/messages/_replies.html.erb
<% if defined?(messageable) && messageable.present? %>
  <% Message.item_messages_ordered(messageable).each do |reply| %>
    <div class="panel panel-default">
      <div class="panel-body message_direct_reply">
        <%= render partial: 'messages/reply', object: reply, locals: {indent: 1} %>
      </div>
    </div>
  <% end %>
<% else %>
  <% @primary_message.replies_ordered.each do |reply| %>
    <div class="panel panel-default">
      <div class="panel-body message_direct_reply">
        <%= render partial: 'messages/reply', object: reply, locals: {indent: 1} %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/messages/_save.js.erb
$("ul.errors").html("")
<% if @message.errors.any? %>
  <% @message.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  if ($(".message_list").length > 0) {
    $(".message_list").html("<%= escape_javascript(render 'messages/index') %>")
  } else if ($(".reply_list").length > 0) {
    $(".reply_list").html("<%= escape_javascript(render 'messages/replies') %>")
  } else if ($(".messageable_message_list").length > 0) {
    $(".messageable_message_list").html("<%= escape_javascript(render partial: 'messages/replies', object: @message.messageable, as: 'messageable') %>")
  }
  if ($(".message_body").length > 0) {
    $(".message_body").html("<%= escape_javascript(render 'messages/message_body') %>")
  }
  if ($(".message_title").length > 0) {
    $(".message_title").html("<%= escape_javascript(render 'messages/message_title') %>")
  }
  $("#message_modal").modal("hide")
<% end %>

app/views/messages/destroy.js.erb
<%= render "save" %>

app/views/messages/inbox.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>All Messages</h1>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to "New Messages", messages_inbox_unread_path, class: "btn btn-info btn-lg margin_top" %>
  </div>
</div>
<div class="message_list margin_top">
  <div id="user_messages">
    <%= render partial: "user_messages", object: @all_messages, as: 'messages' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @all_messages, :renderer => BootstrapPagination::Rails %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>

app/views/messages/inbox_unread.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>New Messages</h1>
  </div>
  <div class="col-xs-4 text-right">
    <%= link_to "All Messages", messages_inbox_path, class: "btn btn-info btn-lg margin_top" %>
  </div>
</div>
<div class="message_list margin_top">
  <div id="user_messages">
    <%= render partial: "user_messages", object: @new_messages, as: 'messages' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @new_messages, :renderer => BootstrapPagination::Rails %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>

app/views/messages/new.js.erb
$("#message_modal").html("<%= escape_javascript(render 'new') %>")
$("#message_modal").modal("show")

app/views/messages/show.html.erb
<div class="row large_margin_bottom">
  <div class="col-xs-1">
    <div class="voting_area large" data-voteable-item="Message<%= @primary_message.id %>">
      <%= render partial: "votes/voting_area", object: @primary_message, as: 'voteable', locals: {} %>
    </div>
  </div>
  <div class="col-xs-7">
    <div class="message_title">
      <%= render "message_title" %>
    </div>
  </div>
  <div class="col-xs-4 text-right">
    <% if @primary_message.user == current_user && @primary_message.deleted.blank? %>
      <%= link_to raw("<strong><span class='glyphicon glyphicon-pencil'></span> Edit</strong>"), edit_message_path(@primary_message, primary_message_id: @primary_message_id), remote: true, class: "btn btn-info btn-lg margin_top" %>
      <%= link_to raw("<strong><span class='glyphicon glyphicon-trash'></span> Delete</strong>"), message_delete_path(@primary_message, primary_message_id: @primary_message_id), remote: true, class: "btn btn-danger btn-lg margin_top" %>
    <% end %>
    <%= link_to raw("<span class='glyphicon glyphicon-share-alt'></span> Reply"), new_message_path(parent_message_id: @primary_message.id, primary_message_id: @primary_message.id), remote: true, class: "btn btn-success btn-lg margin_top" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body message_body">
        <%= render "message_body" %>
      </div>
    </div>
  </div>
</div>

<h3>Replies</h3>
<div class="reply_list">
  <%= render "replies" %>
</div>


<!-- Modal -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>