config/routes.rb
TrainToSend::Application.routes.draw do

  get 'home/index'

  devise_for :users, controllers: { sessions: "users/sessions" }

  authenticate :user do
    resources :climbs do
      get "delete"

      resources :attempts
    end
    get 'quick_send', to: 'climbs#quick_new', as: 'climbs_quick_send_new'
    post 'quick_send', to: 'climbs#quick_create', as: 'climbs_quick_send_create'
    get 'sync_mountain_project', to: 'climbs#sync_mountain_project', as: 'climbs_sync_mountain_project'

    resources :exercise_metrics do
      get "delete"
    end

    resources :exercises, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
    end

    resources :workouts, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
      get "assign", to: 'workouts#assign_new'
      post "assign", to: 'workouts#assign_create'
    end

    resources :macrocycles, only: [:index, :new, :create, :edit, :update, :destroy], :path => "plans" do
      get "delete"
      get "duplicate"
      get "assign", to: 'macrocycles#assign_new'
      post "assign", to: 'macrocycles#assign_create'
    end

    resources :events do
      get "delete"
      get "complete"
      get "print"
    end
    get 'gym_session', to: 'events#gym_session_new'
    post 'gym_session', to: 'events#gym_session_create'
    get 'self_assessment', to: 'events#self_assessment'
    get 'self_assessment/new', to: 'events#self_assessment_new', as: 'self_assessment_new'

    get 'profile', to: 'profile#show'
    get 'profile/edit', to: 'profile#edit'
    get 'profile/start_mountain_project', to: 'profile#start_mountain_project'
    patch 'profile/connect_mountain_project', to: 'profile#connect_mountain_project'
    get 'profile/disconnect_mountain_project', to: 'profile#disconnect_mountain_project'
    get 'profile/progress', to: 'profile#progress'
    get 'profile/:user_id/progress', to: 'profile#progress', as: 'profile_user_progress'
    get 'profile/:user_id/schedule', to: 'profile#schedule', as: 'profile_user_schedule'
    get 'profile/:user_id/events/new', to: 'events#new', as: 'profile_user_events_new'
    get 'profile/:user_id/events/create', to: 'events#create', as: 'profile_user_events_create'
    patch 'profile', to: 'profile#update'

    resources :user_coaches, :path => "coaches", only: [:new, :create, :destroy] do
      get "delete"
    end
    get "coaches/my_students", to: 'user_coaches#my_students'

    resources :users, only: [:index, :show] do
      get "impersonate"
    end
    get "stop_impersonating", to: 'users#stop_impersonating'

    resources :item_shares, :path => "share" do
      get "accept"
      get "reject"
    end

    get 'community/training', to: 'community#training'
    get 'community/my_users', to: 'community#my_users'
    get 'community/my_followers', to: 'community#my_followers'
    get 'community/users/follow/:user_id', to: 'community#user_follow', as: 'community_user_follow'
    get 'community/users/unfollow/:user_id', to: 'community#user_unfollow', as: 'community_user_unfollow'

    resources :goals do
      get "delete"
    end

    resources :messages, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end
    get 'inbox/unread', to: 'messages#inbox_unread', as: 'messages_inbox_unread'
    get 'inbox', to: 'messages#inbox', as: 'messages_inbox'

    resources :votes, only: [:new]

    resources :articles, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end

    get 'comment', to: 'comments#new'
    post 'comment', to: 'comments#create'

    get 'onboarding', to: 'users#onboarding'
    get 'onboarding_skip', to: 'users#onboarding_skip'

  end

  resources :messages, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :exercises, only: [:show]
  resources :workouts, only: [:show]
  resources :macrocycles, only: [:show], :path => "plans"
  get 'community/users', to: 'community#users'
  get 'community/users/:user_id', to: 'community#user', as: 'community_user'

  get 'privacy_policy', to: 'home#privacy_policy'
  get 'terms_of_service', to: 'home#terms_of_service'

  root to: "home#index"

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :set_exercises, :only => [:show, :new, :edit, :update]

  def set_exercises
    if user_signed_in?
      @exercises = current_user.exercises
      @boulder_grades = Climb.bouldering_grades(current_user.grade_format)
      @sport_grades = Climb.sport_grades(current_user.grade_format)
    else
      @exercises = []
      @boulder_grades = Climb.bouldering_grades("wester")
      @sport_grades = Climb.sport_grades("western")
    end
  end

  def index
    @workouts = current_user.workouts.order(created_at: :desc)

    if params[:workout_type].present?
      @workouts = @workouts.where(workout_type: params[:workout_type])
    end

    respond_to do |format|
      format.html
      format.js { render :reload }
      format.json { render json: @workouts, status: :ok, location: @workouts }
    end
  end

  def show
    @workout = Workout.find_by_id(params[:id])
    if @workout.user.allow_profile_view.blank? && @workout.user.id != current_user.id
      @workout = nil
    end
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @workout, status: :ok, location: @workout }
    end
  end

  def new
    @workout = current_user.workouts.new
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @workout, status: :created, location: @workout }
    end
  end

  def create
    @workout = current_user.workouts.new(workout_params)

    respond_to do |format|
      if @workout.save
        @workout.handle_workout_exercises(params[:workout_exercises])
        format.html { redirect_to workouts_path, notice: 'Workout was successfully created.' }
        format.js
        format.json { render json: @workout, status: :created, location: @workout }
      else
        format.html { render action: "new" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @workout = current_user.workouts.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @workout, status: :ok, location: @workout }
    end
  end

  def update
    @workout = current_user.workouts.find_by_id(params[:id])
    respond_to do |format|
      if @workout.update_attributes(workout_params)
        @workout.handle_workout_exercises(params[:workout_exercises])
        format.html { redirect_to workouts_path, notice: 'Workout was successfully updated.' }
        format.js
        format.json { render json: @workout, status: :ok, location: @workout }
      else
        format.html
        format.js
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @workout = current_user.workouts.find_by_id(params[:workout_id])
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def destroy
    @workouts = current_user.workouts.order(created_at: :desc)
    @workout = current_user.workouts.find_by_id(params[:id])
    @workout.destroy
  end

  def duplicate
    @workouts = current_user.workouts.order(created_at: :desc)
    original_workout = Workout.find_by_id(params[:workout_id])
    if original_workout.present? && (original_workout.user.allow_profile_view.present? || original_workout.user.id == current_user.id)
      @workout = original_workout.duplicate(current_user)
    end
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def assign_new
    @students = current_user.students
    @workout = current_user.workouts.find_by_id(params[:workout_id])
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def assign_create
    @workouts = current_user.workouts.order(created_at: :desc)
    @workout = current_user.workouts.find_by_id(params[:workout_id])
    student_ids = current_user.students.pluck(:user_id).uniq
    if params[:student_ids].present?
      params[:student_ids].map(&:to_i).each do |student_id|
        if student_ids.include? student_id
          student = User.find_by_id(student_id)
          new_workout = @workout.duplicate(student)
        end
      end
    end
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:label, :workout_type, :description, :private)
  end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Workout</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @workout.label %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Workout", workout_path(@workout), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/workouts/_index.html.erb
<div class="row">
  <% @workouts.each_with_index do |workout, index| %>
    <%= render workout %>
    <% if index % 3 == 2 %>
  </div><div class="row">
    <% end %>
  <% end %>
</div>

app/views/workouts/_save.js.erb
$("ul.errors").html("")
<% if @workout.errors.any? %>
  <% @workout.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".workout_list").html("<%= escape_javascript(render 'index') %>")
  $("#workout_modal").modal("hide")
<% end %>

app/views/workouts/_workout.html.erb
<div class="col-md-4 col-sm-6 margin_bottom">
  <div class="panel<%= workout.panel_class %>">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-9">
          <h3 class="panel-title">
            <%= link_to simple_format(truncate(workout.label, length: 30)), workout_path(workout) %>
          </h3>
        </div>
        <div class="col-xs-3 text-right">
          <span class="voting_area voting_area_button_small" data-voteable-item="Workout<%= workout.id %>">
            <%= render partial: "votes/voting_area", object: workout, as: 'voteable', locals: {version: "button_small"} %>
          </span>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <%= simple_format(truncate(workout.description, length: 50, separator: ' ')) %>
    </div>
    <div class="panel-footer text-right">
      <% if current_user.students.present? %>
        <%= link_to "Assign", workout_assign_path(workout), remote: true, class: "btn btn-sm btn-default" %>
      <% end %>
      <%= link_to "Duplicate", workout_duplicate_path(workout), remote: true, class: "btn btn-sm btn-success" %>
      <%= link_to "Edit", edit_workout_path(workout), class: "btn btn-sm btn-info" %>
      <%= link_to "Share", new_item_share_path(item_type: "Workout", item_id: workout.id), remote: true, class: "btn btn-sm btn-warning" %>
      <%= link_to "Delete", workout_delete_path(workout), remote: true, class: "btn btn-sm btn-danger" %>
    </div>
  </div>
</div>

app/views/workouts/_workout_exercise.html.erb
<div class="planner_exercise alert<%= exercise.alert_class %> draggable" data-exercise-id="<%= exercise.id %>">
  <span class="exercise_label">
    <%= exercise.label %>
  </span>
  <div class="hidden exercise_metrics">
    <input name="workout_exercises[][id]" type="hidden" value=""/>
    <input name="workout_exercises[][exercise_id]" type="hidden" value="<%= exercise.id %>"/>
    <% exercise.exercise_metrics.each do |exercise_metric| %>
      <div class="form-group text-right">
        <label>
          <%= exercise_metric.label %> <%= exercise_metric.unit_string(true) %>
        </label>
        <input type="hidden" name="workout_exercises[][workout_metrics][][exercise_metric_id]" value="<%= exercise_metric.id %>"/>
        <% if exercise_metric.exercise_metric_type.input_field == "select" %>
          <select name="workout_exercises[][workout_metrics][][value]" class="form-control inline_block" >
            <% if exercise_metric.exercise_metric_type.slug == "boulder-grade" %>
              <%= options_for_select(@boulder_grades) %>
            <% elsif exercise_metric.exercise_metric_type.slug == "sport-grade" %>
              <%= options_for_select(@sport_grades) %>
            <% else %>
              <%= options_from_collection_for_select(exercise_metric.exercise_metric_options, :value, :label) %>
            <% end %>
          </select>
        <% elsif exercise_metric.exercise_metric_type.input_field == "range" %>
          <div class="col-sm-9 pull-right">
            <div class="row slider_container">
              <div class="col-xs-9 no_padding_right">
                <input type="range"
                       name="workout_exercises[][workout_metrics][][value]"
                       min="0"
                       max="100"
                       step="5"
                       value="<%= exercise_metric.default_value.present? ? exercise_metric.default_value : 0 %>"
                       class="completion_slider">
              </div>
              <div class="col-xs-3">
                <span class="slider_value_wrapper alt_font"><span class="slider_value"><%= exercise_metric.default_value.present? ? exercise_metric.default_value : 0 %></span>%</span>
              </div>
            </div>
          </div>
        <% else %>
          <input class="form-control inline_block"
                 name="workout_exercises[][workout_metrics][][value]"
                 type="<%= exercise_metric.exercise_metric_type.input_field %>"
                 value="<%= exercise_metric.default_value %>"
                 placeholder="Baseline Value"
                 <% if exercise_metric.exercise_metric_type_id == ExerciseMetricType::HOLD_SIZE_ID %>
                  step="any"
                 <% end %>
          />
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/workouts/assign_create.js.erb
<%= render "save" %>

app/views/workouts/assign_new.js.erb
$("#workout_modal").html("<%= escape_javascript(render 'assign_new') %>")
$("#workout_modal").modal("show")

app/views/workouts/delete.js.erb
$("#workout_modal").html("<%= escape_javascript(render 'delete') %>")
$("#workout_modal").modal("show")

app/views/workouts/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="inline_block valign_middle margin_right">Update Workout</h1>
    <p>Create a workout.</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-9 col-xs-6">
    <%= render "form" %>
  </div>
  <div class="col-sm-3 col-xs-6">
    <h2>My Exercises</h2>
    <p>(you can drag your exercises to the list and rearrange them)</p>
    <div id="my_exercises">
      <% @exercises.each do |exercise| %>
        <%= render partial: 'workout_exercise', locals: {exercise: exercise} %>
      <% end %>
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="inline_block valign_middle margin_right">Create Workout</h1>
    <p>Create a workout.</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-9 col-xs-6">
    <%= render "form" %>
  </div>
  <div class="col-sm-3 col-xs-6" id="my_exercises">
    <h2>My Exercises</h2>
    <p>(you can drag your exercises to the list and rearrange them)</p>
    <% @exercises.each do |exercise| %>
      <%= render partial: 'workout_exercise', locals: {exercise: exercise} %>
    <% end %>
  </div>
</div>

app/views/workouts/reload.js.erb
$(".workout_list").html("<%= escape_javascript(render 'index') %>")

app/views/workouts/show.html.erb
<div class="row large_margin_bottom">
  <div class="col-xs-8">
    <span class="voting_area voting_area_button valign_middle margin_right" data-voteable-item="Workout<%= @workout.id %>">
      <%= render partial: "votes/voting_area", object: @workout, as: 'voteable', locals: {version: "button"} %>
    </span>
    <h1 class="inline_block valign_middle" style="margin-top: 10px;">
      <%= @workout.label %><small><span class="margin_left valign_text_top label label-<%= @workout.color_class %>"><%= @workout.pretty_type %></span></small>
    </h1>
  </div>
  <div class="col-xs-4 text-right">
    <h3>User: <%= link_to @workout.user.smart_name, community_user_path(@workout.user.id) %></h3>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= @workout.description %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <h4>Metrics</h4>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Exercise</th>
            <th>Options</th>
            <th>Sets</th>
          </tr>
        </thead>
        <tbody>
          <% @workout.workout_exercises_ordered.each do |workout_exercise| %>
            <tr>
              <td>
                <%= link_to workout_exercise.label, exercise_path(workout_exercise.exercise), remote: true %>
              </td>
              <td>
                <% workout_exercise.workout_metrics.ordered_by_metric.each do |workout_metric| %>
                  <label>
                    <%= workout_metric.exercise_metric.label %> <%= workout_metric.exercise_metric.unit_string(true) %>
                  </label>: <%= workout_metric.value %><br/>
                <% end %>
              </td>
              <td>
                <%= workout_exercise.reps %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>


<%= render partial: "messages/messaging_area", object: @workout, as: 'messageable', locals: {} %>


<!-- Modals -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>

<div class="modal fade" id="exercise_modal" tabindex="-1" role="dialog" aria-labelledby="exerciseModal">

</div>

app/views/workouts/show.js.erb
$("#workout_modal").html("<%= escape_javascript(render 'show') %>")
$("#workout_modal").modal("show")

app/views/workouts/update.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="inline_block valign_middle margin_right">Update Workout</h1>
    <p>Create a workout.</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-9 col-xs-6">
    <%= render "form" %>
  </div>
  <div class="col-sm-3 col-xs-6" id="my_exercises">
    <h2>My Exercises</h2>
    <p>(you can drag your exercises to the list and rearrange them)</p>
    <% @exercises.each do |exercise| %>
      <%= render partial: 'workout_exercise', locals: {exercise: exercise} %>
    <% end %>
  </div>
</div>