config/routes.rb
TrainToSend::Application.routes.draw do

  get 'home/index'

  devise_for :users, controllers: { sessions: "users/sessions" }

  authenticate :user do
    resources :climbs do
      get "delete"

      resources :attempts
    end
    get 'quick_send', to: 'climbs#quick_new', as: 'climbs_quick_send_new'
    post 'quick_send', to: 'climbs#quick_create', as: 'climbs_quick_send_create'
    get 'sync_mountain_project', to: 'climbs#sync_mountain_project', as: 'climbs_sync_mountain_project'

    resources :exercise_metrics do
      get "delete"
    end

    resources :exercises, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
    end

    resources :workouts, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
      get "assign", to: 'workouts#assign_new'
      post "assign", to: 'workouts#assign_create'
    end

    resources :macrocycles, only: [:index, :new, :create, :edit, :update, :destroy], :path => "plans" do
      get "delete"
      get "duplicate"
      get "assign", to: 'macrocycles#assign_new'
      post "assign", to: 'macrocycles#assign_create'
    end

    resources :events do
      get "delete"
      get "complete"
      get "print"
    end
    get 'gym_session', to: 'events#gym_session_new'
    post 'gym_session', to: 'events#gym_session_create'
    get 'self_assessment', to: 'events#self_assessment'
    get 'self_assessment/new', to: 'events#self_assessment_new', as: 'self_assessment_new'

    get 'profile', to: 'profile#show'
    get 'profile/edit', to: 'profile#edit'
    get 'profile/start_mountain_project', to: 'profile#start_mountain_project'
    patch 'profile/connect_mountain_project', to: 'profile#connect_mountain_project'
    get 'profile/disconnect_mountain_project', to: 'profile#disconnect_mountain_project'
    get 'profile/progress', to: 'profile#progress'
    get 'profile/:user_id/progress', to: 'profile#progress', as: 'profile_user_progress'
    get 'profile/:user_id/schedule', to: 'profile#schedule', as: 'profile_user_schedule'
    get 'profile/:user_id/events/new', to: 'events#new', as: 'profile_user_events_new'
    get 'profile/:user_id/events/create', to: 'events#create', as: 'profile_user_events_create'
    patch 'profile', to: 'profile#update'

    resources :user_coaches, :path => "coaches", only: [:new, :create, :destroy] do
      get "delete"
    end
    get "coaches/my_students", to: 'user_coaches#my_students'

    resources :users, only: [:index, :show] do
      get "impersonate"
    end
    get "stop_impersonating", to: 'users#stop_impersonating'

    resources :item_shares, :path => "share" do
      get "accept"
      get "reject"
    end

    get 'community/training', to: 'community#training'
    get 'community/my_users', to: 'community#my_users'
    get 'community/my_followers', to: 'community#my_followers'
    get 'community/users/follow/:user_id', to: 'community#user_follow', as: 'community_user_follow'
    get 'community/users/unfollow/:user_id', to: 'community#user_unfollow', as: 'community_user_unfollow'

    resources :goals do
      get "delete"
    end

    resources :messages, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end
    get 'inbox/unread', to: 'messages#inbox_unread', as: 'messages_inbox_unread'
    get 'inbox', to: 'messages#inbox', as: 'messages_inbox'

    resources :votes, only: [:new]

    resources :articles, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end

    get 'comment', to: 'comments#new'
    post 'comment', to: 'comments#create'

    get 'onboarding', to: 'users#onboarding'
    get 'onboarding_skip', to: 'users#onboarding_skip'

  end

  resources :messages, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :exercises, only: [:show]
  resources :workouts, only: [:show]
  resources :macrocycles, only: [:show], :path => "plans"
  get 'community/users', to: 'community#users'
  get 'community/users/:user_id', to: 'community#user', as: 'community_user'

  get 'privacy_policy', to: 'home#privacy_policy'
  get 'terms_of_service', to: 'home#terms_of_service'

  root to: "home#index"

end

app/controllers/climbs_controller.rb
class ClimbsController < ApplicationController
  helper_method :sort_by, :sort_direction, :page, :per_page, :ordered_climbs

  def index
    @climbs = ordered_climbs

    respond_to do |format|
      format.html
      format.js { render :reload }
      format.json { render json: @climbs, status: :ok, location: @climb }
    end
  end

  def show
    @climb = current_user.climbs.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @climb, status: :ok, location: @climb }
    end
  end

  def new
    @boulder_grades = Climb.bouldering_grades(current_user.grade_format)
    @sport_grades = Climb.sport_grades(current_user.grade_format)
    @climb = current_user.climbs.new
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @climb, status: :created, location: @climb }
    end
  end

  def create
    @climbs = current_user.climbs.order(created_at: :desc)
    @climb = current_user.climbs.new(climb_params)
    attempt_params = {}
    if params[:date].present?
      date = params[:date][:redpoint_date]
      if date.present?
        if date[:day].present? && date[:month].present? && date[:year].present?
          redpoint_date = DateTime.strptime("#{date[:year]} #{date[:month]} #{date[:day]}", "%Y %m %d")
          attempt_params[:date] = redpoint_date
          attempt_params[:onsight] = params[:onsight]
          attempt_params[:flash] = params[:flash]
          attempt_params[:completion] = 100
        end
      end
    end

    respond_to do |format|
      if @climb.save
        if attempt_params.present?
          attempt = @climb.attempts.create(attempt_params)
        end
        @climbs = @climbs.sort_by{|c| [c.redpointed ? 0 : 1, c.redpoint_date]}.reverse
        format.html { redirect_to @climb, notice: 'Climb was successfully created.' }
        format.js
        format.json { render json: @climb, status: :created, location: @climb }
      else
        format.html { render action: "new" }
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  def quick_new
    @boulder_grades = Climb.bouldering_grades(current_user.grade_format)
    @sport_grades = Climb.sport_grades(current_user.grade_format)
    @climb = current_user.climbs.new
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @climb, status: :created, location: @climb }
    end
  end

  def quick_create
    @climbs = current_user.climbs.order(created_at: :desc)
    @climb = current_user.climbs.new(climb_params)
    @climb.name = "Gym Climb"
    @climb.outdoor = false
    @climb.location = current_user.gym_name
    onsight = params[:onsight].present?
    flash = params[:flash].present?

    respond_to do |format|
      if @climb.save
        attempt = @climb.attempts.create(completion: 100, date: DateTime.now, onsight: onsight, flash: flash)
        @climbs = @climbs.sort_by{|c| [c.redpointed ? 0 : 1, c.redpoint_date]}.reverse
        format.html { redirect_to @climb, notice: 'Climb was successfully created.' }
        format.js
        format.json { render json: @climb, status: :created, location: @climb }
      else
        format.html { render action: "new" }
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @boulder_grades = Climb.bouldering_grades(current_user.grade_format)
    @sport_grades = Climb.sport_grades(current_user.grade_format)
    @climb = current_user.climbs.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @climb, status: :ok, location: @climb }
    end
  end

  def update
    @climbs = ordered_climbs
    @climb = current_user.climbs.find_by_id(params[:id])
    respond_to do |format|
      if @climb.update_attributes(climb_params)
        @climbs = @climbs.sort_by{|c| [c.redpointed ? 0 : 1, c.redpoint_date]}.reverse
        format.html
        format.js
        format.json { render json: @climb, status: :ok, location: @climb }
      else
        format.html
        format.js
        format.json { render json: @climb.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @climb = current_user.climbs.find_by_id(params[:climb_id])
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def destroy
    @climb = current_user.climbs.find_by_id(params[:id])
    @climb.destroy
    @climbs = ordered_climbs
  end


  def sync_mountain_project
    respond_to do |format|
      if current_user.sync_mountain_project_climbs
        format.html { redirect_to climbs_path, notice: 'Sync complete!' }
        format.js
        format.json { render json: current_user.climbs, status: :ok, location: current_user.climbs }
      else
        format.html { redirect_to climbs_path, notice: 'Something went wrong with the sync :(' }
        format.js
        format.json { render json: nil, status: :unprocessable_entity }
      end
    end
  end

  private
    def climb_params
      params.require(:climb).permit(:name, :location, :climb_type, :grade, :length,
                                    :length_unit, :outdoor, :crimpy, :slopey, :pinchy,
                                    :pockety, :powerful, :dynamic, :endurance, :technical, :notes)
    end

    def sort_by
      legal_sorts = Climb.column_names + ['redpoint_date']
      legal_sorts.include?(params[:sort_by]) ? params[:sort_by] : "redpoint_date"
    end

    def sort_direction
      %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : "desc"
    end

    def page
      (params[:page] || 1).to_i
    end

    def per_page
      (params[:per_page] || 20).to_i
    end

    def ordered_climbs
      if sort_by == "redpoint_date"
        require 'will_paginate/array'
        climbs = current_user.climbs.sort_by{|c| [c.redpointed ? 0 : 1, c.redpoint_date, c.created_at]}
        if sort_direction.downcase == "desc"
          climbs = climbs.reverse
        end
      else
        climbs = current_user.climbs.order("#{sort_by} #{sort_direction}", "id ASC")
      end

      if params[:climb_type].present?
        climbs = climbs.where(climb_type: params[:climb_type])
      end

      if params[:outdoor].present?
        climbs = climbs.where(outdoor: params[:outdoor] == "true")
      end

      #@climbs = @climbs.sort_by{|c| [c.redpointed ? 0 : 1, c.redpoint_date, c.created_at]}.reverse

      climbs = climbs.paginate(:page => page, :per_page => per_page)
      climbs
    end
end

app/helpers/climbs_helper.rb
module ClimbsHelper
end

app/views/climbs/_climb.html.erb
<tr data-climb-id="<%= climb.id %>">
  <td>
    <strong>
      <% if climb.mountain_project_url.present? %>
        <%= link_to simple_format(truncate(climb.name, length: 22)), climb.mountain_project_url, :target => "_blank" %>
      <% else %>
        <%= simple_format(truncate(climb.name, length: 22)) %>
      <% end %>
    </strong>
  </td>
  <td><%= climb.location %></td>
  <td><%= climb.climb_type %></td>
  <td><%= climb.grade_string %></td>
  <td><% unless climb.length.blank? %><%= climb.length %> <%= climb.length_unit_short %><% end %></td>
  <td><%= climb.redpoint_text %></td>
  <td class="text-right">
    <!-- <%= link_to "Add Attempt", new_climb_attempt_path(climb), remote: true, class: "btn btn-success" %> -->
    <%= link_to "Edit", edit_climb_path(climb, sort_by: sort_by, sort_direction: sort_direction, page: page, per_page: per_page), remote: true, class: "btn btn-info" %>
    <%= link_to "Delete", climb_delete_path(climb, sort_by: sort_by, sort_direction: sort_direction, page: page, per_page: per_page), remote: true, class: "btn btn-danger" %>
  </td>
</tr>

app/views/climbs/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Climb</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @climb.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Climb", climb_path(@climb, sort_by: sort_by, sort_direction: sort_direction, page: page, per_page: per_page), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/climbs/_edit.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Climb</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/climbs/_form.html.erb
<%= form_for(@climb, remote: true) do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <%= f.label :location %><br>
          <%= f.text_field :location, class: "form-control location_field" %>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <%= f.label :outdoor %><br>
          <%= f.check_box :outdoor, class: "outdoor_checkbox" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :climb_type %><br>
          <%= f.select(:climb_type, [['Boulder', 'boulder'], ['Sport', 'sport'], ['Trad', 'trad']], {}, {class: "form-control climb_type_select"}) %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :grade %><br>
          <% if @climb.climb_type == "sport" || @climb.climb_type == "trad" %>
            <%= f.select(:grade, @boulder_grades, {}, {class: "form-control boulder_grades hidden", disabled: true}) %>
            <%= f.select(:grade, @sport_grades, {}, {class: "form-control sport_grades"}) %>
          <% else %>
            <%= f.select(:grade, @boulder_grades, {}, {class: "form-control boulder_grades"}) %>
            <%= f.select(:grade, @sport_grades, {}, {class: "form-control sport_grades hidden", disabled: true}) %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <%= f.label :length %><br>
          <%= f.number_field :length, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <%= f.label :length_unit %><br>
          <%= f.select(:length_unit, [['Feet', 'feet'], ['Meters', 'meters']], {}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label "Characteristics" %><br>
          <div class="row">
            <div class="col-xs-6">
              <%= f.check_box :crimpy %>
              <%= f.label :crimpy %><br>
              <%= f.check_box :slopey %>
              <%= f.label :slopey %><br>
              <%= f.check_box :pinchy %>
              <%= f.label :pinchy %><br>
              <%= f.check_box :pockety %>
              <%= f.label :pockety %>
            </div>
            <div class="col-xs-6">
              <%= f.check_box :powerful %>
              <%= f.label :powerful %><br>
              <%= f.check_box :dynamic %>
              <%= f.label :dynamic %><br>
              <%= f.check_box :endurance %>
              <%= f.label :endurance %><br>
              <%= f.check_box :technical %>
              <%= f.label :technical %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if @climb.id.present? %>
      <div class="row">
        <div class="col-xs-12">
          <h4>Attempts</h4>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Completion</th>
                  <th>Notes</th>
                  <th></th>
                </tr>
              </thead>
              <tbody class="exercise_metric_list">
                <% @climb.attempts.each do |attempt| %>
                  <tr>
                    <td>
                      <%= attempt.date.strftime('%m/%d/%Y') %>
                    </td>
                    <td>
                      <%= attempt.completion %>%
                    </td>
                    <td>
                      <% if attempt.onsight.present? %>
                        Onsighted
                      <% elsif attempt.flash.present? %>
                        Flashed
                      <% end %>
                    </td>
                    <td class="text-right">
                      <%= link_to "Edit", edit_climb_attempt_path(@climb, attempt), remote: true, class: "btn btn-info" %>
                      <%= link_to "Delete", climb_attempt_path(@climb, attempt), method: :delete, remote: true, class: "btn btn-danger" %>
                    </td>
                  </tr>
                <% end %>
                <tr>
                  <td colspan="4" class="text-right" style="border-top-width: 0;">
                    <%= link_to "Add Attempt", new_climb_attempt_path(@climb), remote: true, class: "btn btn-success" %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <% else %>
        <div class="row">
          <div class="col-xs-12">
            <div class="form-group">
              <%= f.label "Redpoint Date" %><br>
              <%= select_month(nil, {field_name: "redpoint_date[month]", prompt: 'Month'}, {class: "form-control", style: "display: inline-block; width: auto;"}) %>
              <%= select_day(nil, {field_name: "redpoint_date[day]", prompt: 'Day'}, {class: "form-control", style: "display: inline-block; width: auto;"}) %>
              <%= select_year(nil, {field_name: "redpoint_date[year]", prompt: 'Year'}, {class: "form-control", style: "display: inline-block; width: auto;"}) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <div class="form-group">
              <%= check_box_tag "onsight" %>
              <%= f.label "Onsight" %>
            </div>
            <div class="form-group">
              <%= check_box_tag "flash" %>
              <%= f.label "Flash" %>
            </div>
          </div>
        </div>

      <% end %>
    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <%= f.label :notes %><br>
          <%= f.text_area :notes, class: "form-control", size: "60x8" %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <input type="submit" class="btn btn-primary" value="Save">
  </div>
<% end %>

app/views/climbs/_index.html.erb
<%= render @climbs %>

app/views/climbs/_new.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Add Climb</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/climbs/_quick_form.html.erb
<%= form_for(@climb, url: climbs_quick_send_create_path, remote: true) do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :climb_type %><br>
          <%= f.select(:climb_type, [['Boulder', 'boulder'], ['Sport', 'sport'], ['Trad', 'trad']], {}, {class: "form-control climb_type_select"}) %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :grade %><br>
          <% if @climb.climb_type == "sport" || @climb.climb_type == "trad" %>
            <%= f.select(:grade, @boulder_grades, {}, {class: "form-control boulder_grades hidden", disabled: true}) %>
            <%= f.select(:grade, @sport_grades, {}, {class: "form-control sport_grades"}) %>
          <% else %>
            <%= f.select(:grade, @boulder_grades, {}, {class: "form-control boulder_grades"}) %>
            <%= f.select(:grade, @sport_grades, {}, {class: "form-control sport_grades hidden", disabled: true}) %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= check_box_tag :onsight %>
          <%= label_tag :onsight %>
        </div>
        <div class="form-group">
          <%= check_box_tag :flash %>
          <%= label_tag :flash %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <input type="submit" class="btn btn-primary" value="Save">
  </div>
<% end %>

app/views/climbs/_quick_new.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Add Climb</h4>
    </div>
    <%= render "quick_form" %>
  </div>
</div>

app/views/climbs/delete.js.erb
$("#climb_modal").html("<%= escape_javascript(render 'delete') %>")
$("#climb_modal").modal("show")

app/views/climbs/index.html.erb
<div class="row">
  <div class="col-xs-12 margin_bottom">
    <h1>Climbs</h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-7">
    <%= form_tag("/climbs", method: "get", remote: true, class: "form-inline" ) do %>
      <strong>Filter by:</strong>
      <div class="form-group margin_left">
        <%= select_tag(:climb_type, options_for_select([['Type', ''], ['Boulder', 'boulder'], ['Sport', 'sport'], ['Trad', 'trad']]), class: "form-control") %>
      </div>
      <div class="form-group margin_left">
        <%= select_tag(:outdoor, options_for_select([['Location', ''], ['Outdoor', true], ['Indoor', false]]), class: "form-control") %>
      </div>

      <%= submit_tag("Filter", class: "btn btn-default margin_left") %>
      <!-- <a class="btn" role="button" data-toggle="collapse" href="#advanced_filtering" aria-expanded="false" aria-controls="advanced_filtering">
        More Filters <span class="caret"></span>
      </a>

      <div class="collapse" id="advanced_filtering">
        <div class="margin_top margin_bottom">
          <% if @date_lower.present? %>
            <div class="form-group margin_left">
              <%= label_tag(:climb_type, "From:") %>
              <%= select_month(@date_lower, {field_name: "month_lower"}, {class: "form-control"}) %>
              <%= select_day(@date_lower, {field_name: "day_lower"}, {class: "form-control"}) %>
              <%= select_year(@date_lower, {field_name: "year_lower"}, {class: "form-control"}) %>
            </div>
          <% end %>
          <% if @date_upper.present? %>
            <div class="form-group margin_left">
              <%= label_tag(:climb_type, "To:") %>
              <%= select_month(@date_upper, {field_name: "month_upper"}, {class: "form-control"}) %>
              <%= select_day(@date_upper, {field_name: "day_upper"}, {class: "form-control"}) %>
              <%= select_year(@date_upper, {field_name: "year_upper"}, {class: "form-control"}) %>
            </div>
          <% end %>
        </div>
      </div> -->
    <% end %>
  </div>
  <div class="col-xs-5 text-right">
    <% if current_user.mountain_project_user_id.present? %>
      <%= link_to raw("<span class='glyphicon glyphicon-refresh'></span> Sync"), climbs_sync_mountain_project_path, data: { toggle: 'tooltip', placement: 'top' }, title: "Sync to your Mountain Project account", class: "btn btn-warning btn disable_after_click spin_after_click" %>
    <% end %>
    <%= link_to raw("<span class='glyphicon glyphicon-plus'></span> Add Climb"), new_climb_path, remote: true, class: "btn btn-success btn" %>
    <%= link_to raw("<span class='glyphicon glyphicon-plus'></span> Quick Send"), climbs_quick_send_new_path, remote: true, class: "btn btn-primary btn" %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table class="table table-striped" id="climbs">
        <thead>
          <tr>
            <th><%= sortable "name", "Climb Name" %></th>
            <th><%= sortable "location" %></th>
            <th><%= sortable "type" %></th>
            <th><%= sortable "grade" %></th>
            <th><%= sortable "length" %></th>
            <th><%= sortable "redpoint_date", "Redpointed" %></th>
            <th></th>
          </tr>
        </thead>
        <tbody class="climb_list">
          <%= render "climbs/index" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @climbs, :renderer => BootstrapPagination::Rails %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="climb_modal" tabindex="-1" role="dialog" aria-labelledby="climbModalForm">

</div>

app/views/climbs/new.js.erb
$("#climb_modal").html("<%= escape_javascript(render 'new') %>")
$("#climb_modal").modal("show")

app/views/climbs/quick_create.js.erb
<%= render "save" %>

app/views/climbs/quick_new.js.erb
$("#climb_modal").html("<%= escape_javascript(render 'quick_new') %>")
$("#climb_modal").modal("show")

app/views/climbs/reload.js.erb
$(".climb_list").html("<%= escape_javascript(render 'index') %>")