config/routes.rb
TrainToSend::Application.routes.draw do

  get 'home/index'

  devise_for :users, controllers: { sessions: "users/sessions" }

  authenticate :user do
    resources :climbs do
      get "delete"

      resources :attempts
    end
    get 'quick_send', to: 'climbs#quick_new', as: 'climbs_quick_send_new'
    post 'quick_send', to: 'climbs#quick_create', as: 'climbs_quick_send_create'
    get 'sync_mountain_project', to: 'climbs#sync_mountain_project', as: 'climbs_sync_mountain_project'

    resources :exercise_metrics do
      get "delete"
    end

    resources :exercises, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
    end

    resources :workouts, only: [:index, :new, :create, :edit, :update, :destroy] do
      get "delete"
      get "duplicate"
      get "assign", to: 'workouts#assign_new'
      post "assign", to: 'workouts#assign_create'
    end

    resources :macrocycles, only: [:index, :new, :create, :edit, :update, :destroy], :path => "plans" do
      get "delete"
      get "duplicate"
      get "assign", to: 'macrocycles#assign_new'
      post "assign", to: 'macrocycles#assign_create'
    end

    resources :events do
      get "delete"
      get "complete"
      get "print"
    end
    get 'gym_session', to: 'events#gym_session_new'
    post 'gym_session', to: 'events#gym_session_create'
    get 'self_assessment', to: 'events#self_assessment'
    get 'self_assessment/new', to: 'events#self_assessment_new', as: 'self_assessment_new'

    get 'profile', to: 'profile#show'
    get 'profile/edit', to: 'profile#edit'
    get 'profile/start_mountain_project', to: 'profile#start_mountain_project'
    patch 'profile/connect_mountain_project', to: 'profile#connect_mountain_project'
    get 'profile/disconnect_mountain_project', to: 'profile#disconnect_mountain_project'
    get 'profile/progress', to: 'profile#progress'
    get 'profile/:user_id/progress', to: 'profile#progress', as: 'profile_user_progress'
    get 'profile/:user_id/schedule', to: 'profile#schedule', as: 'profile_user_schedule'
    get 'profile/:user_id/events/new', to: 'events#new', as: 'profile_user_events_new'
    get 'profile/:user_id/events/create', to: 'events#create', as: 'profile_user_events_create'
    patch 'profile', to: 'profile#update'

    resources :user_coaches, :path => "coaches", only: [:new, :create, :destroy] do
      get "delete"
    end
    get "coaches/my_students", to: 'user_coaches#my_students'

    resources :users, only: [:index, :show] do
      get "impersonate"
    end
    get "stop_impersonating", to: 'users#stop_impersonating'

    resources :item_shares, :path => "share" do
      get "accept"
      get "reject"
    end

    get 'community/training', to: 'community#training'
    get 'community/my_users', to: 'community#my_users'
    get 'community/my_followers', to: 'community#my_followers'
    get 'community/users/follow/:user_id', to: 'community#user_follow', as: 'community_user_follow'
    get 'community/users/unfollow/:user_id', to: 'community#user_unfollow', as: 'community_user_unfollow'

    resources :goals do
      get "delete"
    end

    resources :messages, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end
    get 'inbox/unread', to: 'messages#inbox_unread', as: 'messages_inbox_unread'
    get 'inbox', to: 'messages#inbox', as: 'messages_inbox'

    resources :votes, only: [:new]

    resources :articles, only: [:new, :create, :edit, :update, :destroy] do
      get "delete"
    end

    get 'comment', to: 'comments#new'
    post 'comment', to: 'comments#create'

    get 'onboarding', to: 'users#onboarding'
    get 'onboarding_skip', to: 'users#onboarding_skip'

  end

  resources :messages, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :exercises, only: [:show]
  resources :workouts, only: [:show]
  resources :macrocycles, only: [:show], :path => "plans"
  get 'community/users', to: 'community#users'
  get 'community/users/:user_id', to: 'community#user', as: 'community_user'

  get 'privacy_policy', to: 'home#privacy_policy'
  get 'terms_of_service', to: 'home#terms_of_service'

  root to: "home#index"

end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  helper_method :sort_by, :sort_direction, :page, :per_page
  before_filter :set_all_users, :only => [:users, :my_users, :user_follow, :user_unfollow]
  before_filter :set_my_users, :only => [:my_users, :user_follow, :user_unfollow]
  before_filter :set_my_followers, :only => [:my_followers, :user_follow, :user_unfollow]

  def set_all_users
    if sort_by == "follower_count" || sort_by == "workout_count" || sort_by == "name"
      require 'will_paginate/array'
      case sort_by
      when "follower_count"
        @all_users = User.where(allow_profile_view: true).sort_by(&:follower_count)
      when "workout_count"
        @all_users = User.where(allow_profile_view: true).sort_by(&:workout_count)
      when "name"
        @all_users = User.where(allow_profile_view: true).sort_by{|x| x.smart_name.downcase}
      end
      if sort_direction.downcase == "desc"
        @all_users = @all_users.reverse
      end
    else
      @all_users = User.where(allow_profile_view: true).order("#{sort_by} #{sort_direction}", "id ASC")
    end

    @all_users = @all_users.paginate(:page => page, :per_page => per_page)
  end

  def set_my_users
    if sort_by == "follower_count" || sort_by == "workout_count" || sort_by == "name"
      require 'will_paginate/array'
      case sort_by
      when "follower_count"
        @my_users = current_user.my_users.sort_by(&:follower_count)
      when "workout_count"
        @my_users = current_user.my_users.sort_by(&:workout_count)
      when "name"
        @my_users = current_user.my_users.sort_by{|x| x.smart_name.downcase}
      end
      if sort_direction.downcase == "desc"
        @my_users = @my_users.reverse
      end
    else
      @my_users = current_user.my_users.order("#{sort_by} #{sort_direction}", "id ASC")
    end

    @my_users = @my_users.paginate(:page => page, :per_page => per_page)
  end

  def set_my_followers
    if sort_by == "follower_count" || sort_by == "workout_count" || sort_by == "name"
      require 'will_paginate/array'
      case sort_by
      when "follower_count"
        @my_followers = current_user.my_followers.sort_by(&:follower_count)
      when "workout_count"
        @my_followers = current_user.my_followers.sort_by(&:workout_count)
      when "name"
        @my_followers = current_user.my_followers.sort_by{|x| x.smart_name.downcase}
      end
      if sort_direction.downcase == "desc"
        @my_followers = @my_followers.reverse
      end
    else
      @my_followers = current_user.my_followers.order("#{sort_by} #{sort_direction}", "id ASC")
    end

    @my_followers = @my_followers.paginate(:page => page, :per_page => per_page)
  end

  def training

  end

  def users

  end

  def my_users

  end

  def my_followers

  end

  def user
    @user = User.find_by_id(params[:user_id])
  end

  def user_follow
    user = User.find_by_id(params[:user_id])
    if user.present? && user.allow_followers.present? && current_user.is_following(params[:user_id]).blank?
      @user_follower = UserFollower.new(user_id: params[:user_id], follower_id: current_user.id)
      respond_to do |format|
        if @user_follower.save
          format.html { redirect_to @user_follower, notice: 'User was successfully followed.' }
          format.js
          format.json { render json: @user_follower, status: :created, location: @user_follower }
        else
          format.html { render action: "new" }
          format.json { render json: @user_follower.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html
        format.js
        format.json { render json: @user_follower.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_unfollow
    @user_follower = UserFollower.where(user_id: params[:user_id], follower_id: current_user.id)
    if @user_follower.present?
      @user_follower.destroy_all
    end
  end

  private

    def sort_by
      legal_sorts = User.column_names + ['workout_count', 'follower_count', 'name']
      legal_sorts.include?(params[:sort_by]) ? params[:sort_by] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : "asc"
    end

    def page
      (params[:page] || 1).to_i
    end

    def per_page
      (params[:per_page] || 20).to_i
    end

end

app/helpers/community_helper.rb
module CommunityHelper
end

app/views/community/_users.html.erb
<% if defined?(my_users) && my_users.present?
    @users = @my_users
  elsif defined?(my_followers) && my_followers.present?
    @users = @my_followers
  else
    @users = @all_users
  end %>

<% if @users.present? %>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.smart_name, community_user_path(user.id) %></td>
      <td><%= user.created_at.strftime("%b %d, %Y") %></td>
      <td><%= user.workout_count %></td>
      <td><%= user.follower_count %></td>
      <td class="text-right">
        <% if current_user != user && user.allow_followers.present? && user_signed_in? %>
          <% if current_user.is_following(user.id) %>
            <%= link_to "Unfollow", community_user_unfollow_path(user.id, sort_by: sort_by, sort_direction: sort_direction, page: page, per_page: per_page), remote: true, class: "btn btn-danger" %>
          <% else %>
            <%= link_to "Follow", community_user_follow_path(user.id, sort_by: sort_by, sort_direction: sort_direction, page: page, per_page: per_page), remote: true, class: "btn btn-info" %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan="5" class="text-center">
      <% if defined?(my_users) && my_users.present? %>
        Be sure to follow other users so that you can view and copy their workouts.
      <% elsif defined?(my_followers) && my_followers.present? %>
        You don't have any followers yet. Be sure to create some new workouts that might benefit the community.
      <% else %>
        There are no users here, something seems to have gone awry
      <% end %>
    </td>
  </tr>
<% end %>

app/views/community/_users_save.js.erb
if ($(".community_users_list").length > 0) {
  $(".community_users_list").html("<%= escape_javascript(render 'community/users') %>");
}

if ($(".community_my_users_list").length > 0) {
  $(".community_my_users_list").html("<%= escape_javascript(render partial: 'community/users', locals: {my_users: true}) %>");
}

if ($(".community_my_followers_list").length > 0) {
  $(".community_my_followers_list").html("<%= escape_javascript(render partial: 'community/users', locals: {my_followers: true}) %>");
}

app/views/community/all_messages.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>All Messages</h1>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to "New Messages", community_path, class: "btn btn-info btn-lg margin_top" %>
  </div>
</div>
<div class="message_list margin_top">
  <div id="user_messages">
    <%= render partial: "user_messages", object: @all_messages, as: 'messages' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @all_messages, :renderer => BootstrapPagination::Rails %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>

app/views/community/index.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>New Messages</h1>
  </div>
  <div class="col-xs-4 text-right">
    <%= link_to "All Messages", community_messages_path, class: "btn btn-info btn-lg margin_top" %>
  </div>
</div>
<div class="message_list margin_top">
  <div id="user_messages">
    <%= render partial: "user_messages", object: @new_messages, as: 'messages' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @new_messages, :renderer => BootstrapPagination::Rails %>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>

app/views/community/my_followers.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>My Followers</h1>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to "View My Users", community_my_users_path, class: "btn btn-info btn-lg margin_top" %>
    <%= link_to "View All Users", community_users_path, class: "btn btn-success btn-lg margin_top" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table class="table table-striped" id="community_my_followers">
        <thead>
          <tr>
            <th><%= sortable "name" %></th>
            <th><%= sortable "created_at", "Member Since" %></th>
            <th><%= sortable "workout_count", "Workouts" %></th>
            <th><%= sortable "follower_count", "Followers" %></th>
            <th></th>
          </tr>
        </thead>
        <tbody class="community_my_followers_list">
          <%= render partial: "users", locals: {my_followers: true} %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @my_followers, :renderer => BootstrapPagination::Rails %>
  </div>
</div>

app/views/community/my_users.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Users I Follow</h1>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to "View My Followers", community_my_followers_path, class: "btn btn-info btn-lg margin_top" %>
    <%= link_to "View All Users", community_users_path, class: "btn btn-success btn-lg margin_top" %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table class="table table-striped" id="community_users">
        <thead>
          <tr>
            <th><%= sortable "name" %></th>
            <th><%= sortable "created_at", "Member Since" %></th>
            <th><%= sortable "workout_count", "Workouts" %></th>
            <th><%= sortable "follower_count", "Followers" %></th>
            <th></th>
          </tr>
        </thead>
        <tbody class="community_my_users_list">
          <%= render partial: "users", locals: {my_users: true} %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @my_users, :renderer => BootstrapPagination::Rails %>
  </div>
</div>

app/views/community/user.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>
      <%= @user.smart_name %>'s Profile
    </h1>
  </div>
  <div class="col-xs-4 text-right">
    <% if current_user != @user && user_signed_in? %>
      <%= link_to raw("<span class='glyphicon glyphicon-envelope'></span> Message User"), new_message_path(messageable_type: "User", messageable_id: @user.id), remote: true, class: "btn btn-success btn-lg margin_top" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <h3>Recent Progress</h3>
    <% if @user.should_show_climb_data? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Best Climbs</h3>
        </div>
        <div class="panel-body">
            <div class="build_line" <% @user.climb_graph_data.each_with_index do |line_data, index| %>
                                        data-primary-name-<%= index %> = "<%= line_data[:name] %>"
                                        data-primary-value-<%= index %> = "<%= line_data[:value] %>"
                                        data-primary-tooltip-value-<%= index %> = "<%= line_data[:tooltip_value] %>"
                                    <% end %>></div>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-xs-10">
          <div class="well">
            This user doesn't have enough climbing data yet.
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h3>Exercises</h3>
    <div class="side_scrolling">
      <% @user.public_exercises.each do |exercise| %>
        <div class="col-md-3 col-sm-6 inline_block float_none valign_top">
          <div class="panel<%= exercise.panel_class %>">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-9">
                  <h3 class="panel-title">
                    <%= link_to simple_format(truncate(exercise.label, length: 22)), exercise_path(exercise) %>
                  </h3>
                </div>
                <div class="col-xs-3 text-right">
                  <span class="voting_area voting_area_button_small" data-voteable-item="Exercise<%= exercise.id %>">
                    <%= render partial: "votes/voting_area", object: exercise, as: 'voteable', locals: {version: "button_small"} %>
                  </span>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <%= simple_format(truncate(exercise.description, length: 50, separator: ' ')) %>
            </div>
            <div class="panel-footer text-right">
              <% if user_signed_in? %>
                <%= link_to "Duplicate", exercise_duplicate_path(exercise), remote: true, class: "btn btn-success disable_after_click_remote" %>
              <% end %>
              <%= link_to "View", exercise_path(exercise), remote: true, class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h3>Workouts</h3>
    <div class="side_scrolling">
      <% @user.public_workouts.each do |workout| %>
        <div class="col-md-3 col-sm-6 inline_block float_none valign_top">
          <div class="panel<%= workout.panel_class %>">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-9">
                  <h3 class="panel-title">
                    <%= link_to simple_format(truncate(workout.label, length: 22)), workout_path(workout) %>
                  </h3>
                </div>
                <div class="col-xs-3 text-right">
                  <span class="voting_area voting_area_button_small" data-voteable-item="Workout<%= workout.id %>">
                    <%= render partial: "votes/voting_area", object: workout, as: 'voteable', locals: {version: "button_small"} %>
                  </span>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <%= simple_format(truncate(workout.description, length: 50, separator: ' ')) %>
            </div>
            <div class="panel-footer text-right">
              <% if user_signed_in? %>
                <%= link_to "Duplicate", workout_duplicate_path(workout), remote: true, class: "btn btn-success disable_after_click_remote" %>
              <% end %>
              <%= link_to "View", workout_path(workout), remote: true, class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h3>Plans</h3>
    <div class="side_scrolling">
      <% @user.public_macrocycles.each do |macrocycle| %>
        <div class="col-md-3 col-sm-6 inline_block float_none valign_top">
          <div class="panel<%= macrocycle.panel_class %>">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-9">
                  <h3 class="panel-title">
                    <%= link_to simple_format(truncate(macrocycle.label, length: 22)), macrocycle_path(macrocycle) %>
                  </h3>
                </div>
                <div class="col-xs-3 text-right">
                  <span class="voting_area voting_area_button_small" data-voteable-item="Macrocycle<%= macrocycle.id %>">
                    <%= render partial: "votes/voting_area", object: macrocycle, as: 'voteable', locals: {version: "button_small"} %>
                  </span>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <%= pluralize(macrocycle.duration_weeks, 'Week') %>
            </div>
            <div class="panel-footer text-right">
              <% if user_signed_in? %>
                <%= link_to "Duplicate", macrocycle_duplicate_path(macrocycle), remote: true, class: "btn btn-success disable_after_click_remote" %>
              <% end %>
              <%= link_to "View", macrocycle_path(macrocycle), remote: true, class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h3>Goals</h3>
    <div class="side_scrolling">
      <% @user.public_goals.each do |goal| %>
        <div class="col-md-3 col-sm-6 inline_block float_none valign_top">
          <div class="panel<%= goal.panel_class %>">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-9">
                  <h3 class="panel-title"><%= simple_format(truncate(goal.label, length: 22)) %></h3>
                </div>
                <div class="col-xs-3 text-right">
                  <span class="voting_area voting_area_button_small" data-voteable-item="Goal<%= goal.id %>">
                    <%= render partial: "votes/voting_area", object: goal, as: 'voteable', locals: {version: "button_small"} %>
                  </span>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <div class="build_donut"
                   data-goal-name="<%= goal.label %>"
                   data-goal-value="100"
                   data-user-value="<%= goal.percent_complete %>"
                   data-number-decorator="%"></div>
              Deadline: <%= goal.deadline.strftime('%m/%d/%Y') if goal.deadline.present? %><br/>
              <% if goal.sub_goals.present? %>
                Subgoals:<br/>
                <ul>
                  <% goal.sub_goals.each do |sub_goal| %>
                    <%= render partial: 'goals/sub_goal', object: sub_goal, locals: {indent: 1, table_row: false, display_links: false} %>
                  <% end %>
                </ul>
              <% end %>
            </div>
            <!-- <div class="panel-footer text-right">

            </div> -->
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modals -->
<div class="modal fade" id="exercise_modal" tabindex="-1" role="dialog" aria-labelledby="exerciseModal">

</div>

<div class="modal fade" id="workout_modal" tabindex="-1" role="dialog" aria-labelledby="workoutModal">

</div>

<div class="modal fade" id="macrocycle_modal" tabindex="-1" role="dialog" aria-labelledby="macrocycleModal">

</div>

<!-- Modal -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="messageModal">

</div>

app/views/community/user_follow.js.erb
<%= render "users_save" %>

app/views/community/user_unfollow.js.erb
<%= render "users_save" %>

app/views/community/users.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>All Users</h1>
  </div>
  <div class="col-xs-6 text-right">
    <% if user_signed_in? %>
      <%= link_to "View My Followers", community_my_followers_path, class: "btn btn-info btn-lg margin_top" %>
      <%= link_to "View My Users", community_my_users_path, class: "btn btn-success btn-lg margin_top" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table class="table table-striped" id="community_users">
        <thead>
          <tr>
            <th><%= sortable "name" %></th>
            <th><%= sortable "created_at", "Member Since" %></th>
            <th><%= sortable "workout_count", "Workouts" %></th>
            <th><%= sortable "follower_count", "Followers" %></th>
            <th></th>
          </tr>
        </thead>
        <tbody class="community_users_list">
          <%= render "users" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <%= will_paginate @all_users, :renderer => BootstrapPagination::Rails %>
  </div>
</div>